import { db } from "@workspace/db";
import {
  usersTable,
  agenciesTable,
  propertiesTable,
  propertyMediaTable,
  leadsTable,
  appointmentsTable,
  estimationsTable,
  activityLogsTable,
} from "@workspace/db";
import crypto from "crypto";

async function hashPassword(password: string): Promise<string> {
  return new Promise((resolve, reject) => {
    const salt = crypto.randomBytes(16).toString("hex");
    crypto.scrypt(password, salt, 64, (err, derivedKey) => {
      if (err) reject(err);
      resolve(`${salt}:${derivedKey.toString("hex")}`);
    });
  });
}

async function seed() {
  console.log("Seeding database...");

  // 1. Create agencies
  const [agency1, agency2] = await db.insert(agenciesTable).values([
    {
      name: "I.D.A Immobilier - Marignane",
      email: "contact@ida-immobilier.com",
      phone: "+33 6 66 37 17 37",
      address: "16 av de la 1ère armée française",
      city: "Marignane",
      postalCode: "13700",
      website: "https://www.ida-immobilier.com",
      status: "active",
    },
    {
      name: "I.D.A Immobilier - Marseille",
      email: "marseille@ida-immobilier.fr",
      phone: "04 91 00 00 02",
      address: "45 Rue de la République",
      city: "Marseille",
      postalCode: "13001",
      website: "https://www.ida-immobilier.fr",
      status: "active",
    },
  ]).returning().onConflictDoNothing();

  if (!agency1) { console.log("Agencies already exist, skipping..."); return; }

  // 2. Create users
  const passwords = {
    super: await hashPassword("superadmin123"),
    admin: await hashPassword("admin123"),
    manager: await hashPassword("manager123"),
    agent: await hashPassword("agent123"),
    client: await hashPassword("client123"),
  };

  const [superadmin, admin, manager, agent1, agent2, client1, client2] = await db.insert(usersTable).values([
    {
      email: "superadmin@ida-immobilier.fr",
      passwordHash: passwords.super,
      firstName: "Pierre",
      lastName: "Dubois",
      role: "superadmin",
      phone: "06 10 00 00 01",
      agencyId: agency1.id,
      isActive: true,
    },
    {
      email: "admin@ida-immobilier.fr",
      passwordHash: passwords.admin,
      firstName: "Marie",
      lastName: "Laurent",
      role: "admin",
      phone: "06 10 00 00 02",
      agencyId: agency1.id,
      isActive: true,
    },
    {
      email: "manager@ida-immobilier.fr",
      passwordHash: passwords.manager,
      firstName: "Jean-Claude",
      lastName: "Martin",
      role: "agency_manager",
      phone: "06 10 00 00 03",
      agencyId: agency1.id,
      isActive: true,
    },
    {
      email: "agent1@ida-immobilier.fr",
      passwordHash: passwords.agent,
      firstName: "Sophie",
      lastName: "Bernard",
      role: "agent",
      phone: "06 10 00 00 04",
      agencyId: agency1.id,
      isActive: true,
    },
    {
      email: "agent2@ida-immobilier.fr",
      passwordHash: passwords.agent,
      firstName: "Thomas",
      lastName: "Petit",
      role: "agent",
      phone: "06 10 00 00 05",
      agencyId: agency2.id,
      isActive: true,
    },
    {
      email: "client1@example.fr",
      passwordHash: passwords.client,
      firstName: "Isabelle",
      lastName: "Moreau",
      role: "client",
      phone: "06 20 00 00 01",
      isActive: true,
    },
    {
      email: "client2@example.fr",
      passwordHash: passwords.client,
      firstName: "François",
      lastName: "Leroy",
      role: "client",
      phone: "06 20 00 00 02",
      isActive: true,
    },
  ]).returning();

  console.log("Users created");

  // 3. Create properties
  const propertiesData = [
    {
      title: "Villa de prestige avec piscine - Vue mer panoramique",
      type: "villa" as const,
      status: "published" as const,
      address: "15 Chemin des Belles Vues",
      postalCode: "13700",
      city: "Marignane",
      department: "Bouches-du-Rhône",
      region: "Provence-Alpes-Côte d'Azur",
      salePrice: "1250000",
      livingArea: 320,
      landArea: 2500,
      rooms: 8,
      bedrooms: 5,
      bathrooms: 3,
      floor: 0,
      yearBuilt: 2010,
      dpeRating: "B",
      gesRating: "B",
      hasTerrace: true,
      hasGarage: true,
      hasPool: true,
      hasGarden: true,
      hasAirConditioning: true,
      hasFiber: true,
      shortDescription: "Majestueuse villa de prestige offrant une vue mer exceptionnelle. Architecte réputé, prestations haut de gamme, grand terrain paysagé avec piscine à débordement.",
      fullDescription: "Nichée dans un écrin de verdure à Marignane, cette villa d'exception vous accueille dans 320 m² de vie raffinée. Conçue par un architecte de renom, elle conjugue harmonieusement le charme provençal et l'élégance contemporaine. Au rez-de-chaussée, un vaste séjour lumineux s'ouvre sur une terrasse panoramique, la cuisine équipée dernière génération, une suite parentale et un bureau. L'étage accueille quatre chambres supplémentaires avec leurs salles d'eau privatives. La piscine à débordement et le jardin paysagé complètent ce bien d'exception.",
      metaTitle: "Villa prestige vue mer Marignane - I.D.A Immobilier",
      agencyId: agency1.id,
      ownerAgentId: agent1.id,
      currentAgentId: agent1.id,
      viewCount: 234,
      favoriteCount: 18,
    },
    {
      title: "Appartement T4 - Résidence sécurisée avec terrasse",
      type: "apartment" as const,
      status: "published" as const,
      address: "8 Avenue de la Méditerranée",
      postalCode: "13700",
      city: "Marignane",
      department: "Bouches-du-Rhône",
      region: "Provence-Alpes-Côte d'Azur",
      salePrice: "285000",
      livingArea: 92,
      rooms: 4,
      bedrooms: 3,
      bathrooms: 2,
      floor: 3,
      totalFloors: 5,
      yearBuilt: 2018,
      dpeRating: "C",
      gesRating: "C",
      hasBalcony: true,
      hasParking: true,
      hasElevator: true,
      hasFiber: true,
      shortDescription: "Bel appartement T4 en résidence sécurisée avec gardien, grande terrasse, parking double et cave. Secteur calme et résidentiel.",
      fullDescription: "Situé au 3ème étage d'une résidence récente avec gardien, cet appartement T4 de 92 m² offre un cadre de vie agréable et sécurisé. Le séjour de 35 m² s'ouvre sur une grande terrasse exposée sud. La cuisine équipée, trois chambres lumineuses, deux salles de bain, un parking double et une cave complètent ce bien. Résidence calme en secteur résidentiel prisé.",
      agencyId: agency1.id,
      ownerAgentId: agent1.id,
      currentAgentId: agent1.id,
      viewCount: 156,
      favoriteCount: 12,
    },
    {
      title: "Maison de village rénovée - Cachet provençal",
      type: "house" as const,
      status: "published" as const,
      address: "3 Rue des Platanes",
      postalCode: "13800",
      city: "Istres",
      department: "Bouches-du-Rhône",
      region: "Provence-Alpes-Côte d'Azur",
      salePrice: "389000",
      livingArea: 145,
      landArea: 400,
      rooms: 6,
      bedrooms: 4,
      bathrooms: 2,
      floor: 0,
      yearBuilt: 1960,
      dpeRating: "D",
      gesRating: "D",
      hasTerrace: true,
      hasGarden: true,
      hasCellar: true,
      shortDescription: "Authentique maison de village entièrement rénovée, alliant charme provençal et confort moderne. Terrasse ombragée, jardin, cave.",
      fullDescription: "Au cœur du vieux village d'Istres, cette maison de caractère de 145 m² a été entièrement rénovée avec soin pour préserver son âme tout en apportant les conforts modernes. Les magnifiques pierres apparentes, les poutres en chêne et les tomettes anciennes créent une atmosphère chaleureuse et authentique. Cuisine ouverte, séjour spacieux avec cheminée, quatre chambres à l'étage. Belle terrasse ombragée par un imposant platane et jardin privatif avec vue sur le village.",
      agencyId: agency1.id,
      ownerAgentId: agent1.id,
      currentAgentId: agent1.id,
      viewCount: 98,
      favoriteCount: 7,
    },
    {
      title: "Appartement T3 avec vue port - Marseille 2ème",
      type: "apartment" as const,
      status: "published" as const,
      address: "22 Quai du Port",
      postalCode: "13002",
      city: "Marseille",
      department: "Bouches-du-Rhône",
      region: "Provence-Alpes-Côte d'Azur",
      salePrice: "420000",
      livingArea: 75,
      rooms: 3,
      bedrooms: 2,
      bathrooms: 1,
      floor: 4,
      totalFloors: 6,
      yearBuilt: 1925,
      dpeRating: "E",
      gesRating: "D",
      hasBalcony: true,
      hasFiber: true,
      shortDescription: "Appartement Haussmannien entièrement rénové avec vue imprenable sur le Vieux-Port. Parquet ancien, moulures, hauteur sous plafond exceptionnelle.",
      fullDescription: "Coup de cœur assuré pour cet appartement de caractère situé dans un immeuble Haussmannien, à deux pas du célèbre Vieux-Port de Marseille. Entièrement rénové avec des matériaux nobles, il conserve tout le cachet de l'époque : parquet point de Hongrie, moulures au plafond, hauteur sous plafond de 3,20m. Vue spectaculaire sur le Vieux-Port depuis le séjour et le balcon filant. Cuisine ouverte moderne, deux chambres, salle de bain en marbre.",
      agencyId: agency2.id,
      ownerAgentId: agent2.id,
      currentAgentId: agent2.id,
      viewCount: 312,
      favoriteCount: 28,
    },
    {
      title: "Villa contemporaine - Aix-en-Provence Est",
      type: "villa" as const,
      status: "published" as const,
      address: "9 Impasse du Moulin",
      postalCode: "13100",
      city: "Aix-en-Provence",
      department: "Bouches-du-Rhône",
      region: "Provence-Alpes-Côte d'Azur",
      salePrice: "875000",
      livingArea: 210,
      landArea: 1200,
      rooms: 7,
      bedrooms: 4,
      bathrooms: 3,
      floor: 0,
      yearBuilt: 2019,
      dpeRating: "A",
      gesRating: "A",
      hasTerrace: true,
      hasGarage: true,
      hasPool: true,
      hasAirConditioning: true,
      hasFiber: true,
      hasParking: true,
      shortDescription: "Splendide villa contemporaine BBC, piscine à débordement, finitions haut de gamme. Secteur résidentiel prisé d'Aix-en-Provence.",
      fullDescription: "Construite en 2019 aux normes BBC, cette villa contemporaine conjugue performance énergétique et élégance. 210 m² de vie organisés sur plain-pied autour d'un patio central baigné de lumière. Vaste séjour de 60 m² ouvert sur la terrasse et la piscine à débordement, cuisine de chef entièrement équipée, suite parentale avec dressing et spa, trois chambres supplémentaires. Domaine paysagé de 1200 m² en secteur calme et sécurisé proche des axes autoroutiers.",
      agencyId: agency2.id,
      ownerAgentId: agent2.id,
      currentAgentId: agent2.id,
      viewCount: 187,
      favoriteCount: 21,
    },
    {
      title: "Studio meublé - Location - Centre Marignane",
      type: "apartment" as const,
      status: "published" as const,
      address: "6 Place de la République",
      postalCode: "13700",
      city: "Marignane",
      department: "Bouches-du-Rhône",
      region: "Provence-Alpes-Côte d'Azur",
      rentalPrice: "550",
      charges: "75",
      livingArea: 28,
      rooms: 1,
      bedrooms: 0,
      bathrooms: 1,
      floor: 2,
      yearBuilt: 1980,
      dpeRating: "D",
      gesRating: "C",
      hasFiber: true,
      shortDescription: "Studio entièrement meublé et équipé au cœur de Marignane. Idéal pour étudiant ou professionnel en déplacement. Toutes commodités à pied.",
      fullDescription: "Studio fonctionnel et meublé de 28 m² situé au 2ème étage d'un immeuble de centre-ville. Espace de vie avec coin cuisine équipé, salle de bain avec douche, nombreux rangements. Lumineux grâce à ses deux fenêtres sur rue. Internet fibre inclus. Accès facile aux transports en commun, commerces et restaurants.",
      agencyId: agency1.id,
      ownerAgentId: agent1.id,
      currentAgentId: agent1.id,
      viewCount: 67,
      favoriteCount: 4,
    },
    {
      title: "Terrain à bâtir - Secteur prisé - 1200 m²",
      type: "land" as const,
      status: "published" as const,
      address: "Route des Collines",
      postalCode: "13700",
      city: "Marignane",
      department: "Bouches-du-Rhône",
      region: "Provence-Alpes-Côte d'Azur",
      salePrice: "195000",
      landArea: 1200,
      rooms: 0,
      bedrooms: 0,
      bathrooms: 0,
      shortDescription: "Beau terrain viabilisé en secteur résidentiel calme, orienté sud, avec belles vues dégagées. Permis de construire accordé pour villa 200 m².",
      fullDescription: "Rare opportunité : terrain de 1200 m² parfaitement orienté sud dans un secteur résidentiel recherché de Marignane. Toutes viabilités en limite de terrain (eau, électricité, gaz, fibre). Permis de construire accordé pour la construction d'une villa de 200 m² avec piscine. Vue dégagée sur les collines de Provence. Environnement calme et sécurisé.",
      agencyId: agency1.id,
      ownerAgentId: agent1.id,
      currentAgentId: agent1.id,
      viewCount: 43,
      favoriteCount: 3,
    },
    {
      title: "Appartement T5 - Dernier étage - Terrasse 80m²",
      type: "apartment" as const,
      status: "published" as const,
      address: "33 Boulevard Michelet",
      postalCode: "13700",
      city: "Marignane",
      department: "Bouches-du-Rhône",
      region: "Provence-Alpes-Côte d'Azur",
      salePrice: "520000",
      livingArea: 130,
      rooms: 5,
      bedrooms: 4,
      bathrooms: 2,
      floor: 7,
      totalFloors: 7,
      yearBuilt: 2015,
      dpeRating: "B",
      gesRating: "B",
      hasTerrace: true,
      hasParking: true,
      hasElevator: true,
      hasAirConditioning: true,
      hasFiber: true,
      shortDescription: "Penthouse exceptionnel au dernier étage, vaste terrasse de 80 m² avec vue panoramique à 360°. Grand séjour, 4 chambres, deux parkings.",
      fullDescription: "Penthouse d'exception occupant tout le dernier étage de cette résidence sécurisée. 130 m² intérieurs auxquels s'ajoutent une terrasse de 80 m² offrant une vue panoramique à 360° sur Marignane, l'étang de Berre et les collines. Séjour double de 45 m², cuisine de chef, quatre chambres dont une suite parentale avec dressing, deux salles de bain. Climatisation réversible, double parking en sous-sol et cave.",
      agencyId: agency1.id,
      ownerAgentId: agent1.id,
      currentAgentId: agent1.id,
      viewCount: 278,
      favoriteCount: 24,
    },
    {
      title: "Local commercial - Emplacement n°1 - 180 m²",
      type: "commercial" as const,
      status: "published" as const,
      address: "1 Place de l'Hôtel de Ville",
      postalCode: "13700",
      city: "Marignane",
      department: "Bouches-du-Rhône",
      region: "Provence-Alpes-Côte d'Azur",
      salePrice: "450000",
      livingArea: 180,
      rooms: 4,
      bedrooms: 0,
      bathrooms: 1,
      floor: 0,
      yearBuilt: 1975,
      dpeRating: "E",
      gesRating: "D",
      shortDescription: "Local commercial idéalement situé en plein cœur de Marignane, forte visibilité, vitrine de 12 mètres, grande réserve, cave.",
      fullDescription: "Emplacement numéro 1 au cœur de Marignane, en face de la mairie. Ce local commercial de 180 m² dispose d'une vitrine exceptionnelle de 12 mètres, d'un espace principal lumineux de 120 m², d'une grande réserve de 40 m², d'un bureau et d'une cave. Fort passage piétonnier et proximité immédiate de toutes commodités. Idéal pour commerce de bouche, prêt-à-porter ou services.",
      agencyId: agency1.id,
      ownerAgentId: agent1.id,
      currentAgentId: agent1.id,
      viewCount: 89,
      favoriteCount: 6,
    },
    {
      title: "Maison de maître - Domaine viticole - 15 ha",
      type: "house" as const,
      status: "draft" as const,
      address: "Domaine de la Garrigue",
      postalCode: "13110",
      city: "Port-de-Bouc",
      department: "Bouches-du-Rhône",
      region: "Provence-Alpes-Côte d'Azur",
      salePrice: "2800000",
      livingArea: 450,
      landArea: 150000,
      rooms: 12,
      bedrooms: 8,
      bathrooms: 5,
      floor: 0,
      yearBuilt: 1890,
      dpeRating: "G",
      gesRating: "F",
      hasTerrace: true,
      hasPool: true,
      hasGarden: true,
      hasCellar: true,
      shortDescription: "Propriété d'exception, maison de maître du XIXe siècle sur 15 hectares de domaine viticole en production. Caves, chais, gîtes.",
      fullDescription: "Propriété d'exception à quelques minutes de Marignane, cette maison de maître du XIXe siècle trône au cœur d'un domaine viticole de 15 hectares en production AOC Côtes de Provence. La demeure principale de 450 m² comprend 8 chambres, grands salons de réception, bibliothèque, cuisine professionnelle. Un gîte de 120 m² et deux maisonnettes complètent l'ensemble. Caves, chais, chaudière, matériel agricole inclus. Rare investissement patrimonial.",
      agencyId: agency1.id,
      ownerAgentId: agent1.id,
      currentAgentId: agent1.id,
      viewCount: 45,
      favoriteCount: 9,
    },
  ];

  const insertedProperties = await db.insert(propertiesTable).values(propertiesData).returning();
  console.log(`${insertedProperties.length} properties created`);

  // 4. Add placeholder media (real images via description, agent will use generated images in frontend)
  const mediaData = [
    // Villa prestige (property 0)
    { propertyId: insertedProperties[0].id, url: "https://images.unsplash.com/photo-1613977257363-707ba9348227?w=1200&q=80", type: "photo" as const, caption: "Vue façade principale", order: 0 },
    { propertyId: insertedProperties[0].id, url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=80", type: "photo" as const, caption: "Piscine à débordement", order: 1 },
    { propertyId: insertedProperties[0].id, url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&q=80", type: "photo" as const, caption: "Séjour", order: 2 },
    // Appartement T4 (property 1)
    { propertyId: insertedProperties[1].id, url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&q=80", type: "photo" as const, caption: "Façade résidence", order: 0 },
    { propertyId: insertedProperties[1].id, url: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200&q=80", type: "photo" as const, caption: "Terrasse", order: 1 },
    // Maison Istres (property 2)
    { propertyId: insertedProperties[2].id, url: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1200&q=80", type: "photo" as const, caption: "Maison de village", order: 0 },
    // Marseille port (property 3)
    { propertyId: insertedProperties[3].id, url: "https://images.unsplash.com/photo-1567496898669-ee935f5f647a?w=1200&q=80", type: "photo" as const, caption: "Vue Vieux-Port", order: 0 },
    { propertyId: insertedProperties[3].id, url: "https://images.unsplash.com/photo-1599809275671-b5942cabc7a2?w=1200&q=80", type: "photo" as const, caption: "Séjour", order: 1 },
    // Villa Aix (property 4)
    { propertyId: insertedProperties[4].id, url: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=1200&q=80", type: "photo" as const, caption: "Villa contemporaine", order: 0 },
    { propertyId: insertedProperties[4].id, url: "https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?w=1200&q=80", type: "photo" as const, caption: "Piscine", order: 1 },
    // Penthouse (property 7)
    { propertyId: insertedProperties[7].id, url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&q=80", type: "photo" as const, caption: "Terrasse panoramique", order: 0 },
  ];

  await db.insert(propertyMediaTable).values(mediaData);
  console.log(`${mediaData.length} media items created`);

  // 5. Create leads
  await db.insert(leadsTable).values([
    {
      firstName: "Adrien",
      lastName: "Dupont",
      email: "adrien.dupont@gmail.com",
      phone: "06 30 00 00 01",
      source: "property_inquiry",
      status: "new",
      message: "Bonjour, je suis intéressé par la villa avec piscine. Pouvez-vous me contacter ?",
      propertyId: insertedProperties[0].id,
      assignedAgentId: agent1.id,
      agencyId: agency1.id,
    },
    {
      firstName: "Claire",
      lastName: "Fontaine",
      email: "c.fontaine@hotmail.fr",
      phone: "06 30 00 00 02",
      source: "estimation_request",
      status: "contacted",
      message: "Je souhaite estimer mon appartement à Marignane.",
      assignedAgentId: agent1.id,
      agencyId: agency1.id,
    },
    {
      firstName: "Maxime",
      lastName: "Garnier",
      email: "maxime.garnier@free.fr",
      phone: "06 30 00 00 03",
      source: "contact_form",
      status: "qualified",
      message: "Recherche appartement T3 ou T4 à Marseille, budget 400 000€.",
      assignedAgentId: agent2.id,
      agencyId: agency2.id,
    },
    {
      firstName: "Léa",
      lastName: "Rousseau",
      email: "lea.rousseau@yahoo.fr",
      phone: "06 30 00 00 04",
      source: "property_inquiry",
      status: "won",
      message: "Intéressée par l'appartement T3 vue port.",
      propertyId: insertedProperties[3].id,
      assignedAgentId: agent2.id,
      agencyId: agency2.id,
    },
    {
      firstName: "Bertrand",
      lastName: "Marchal",
      email: "b.marchal@gmail.com",
      phone: "06 30 00 00 05",
      source: "contact_form",
      status: "new",
      message: "Recherche villa pour ma famille, budget 1 million €, région Aix-Marseille.",
      assignedAgentId: agent1.id,
      agencyId: agency1.id,
    },
  ]);
  console.log("Leads created");

  // 6. Create appointments
  const future1 = new Date(); future1.setDate(future1.getDate() + 2);
  const future2 = new Date(); future2.setDate(future2.getDate() + 5);
  const past1 = new Date(); past1.setDate(past1.getDate() - 3);

  await db.insert(appointmentsTable).values([
    {
      type: "visit",
      status: "confirmed",
      scheduledAt: future1,
      durationMinutes: 60,
      propertyId: insertedProperties[0].id,
      agentId: agent1.id,
      clientId: client1.id,
      notes: "Client très motivé, vient avec son architecte.",
    },
    {
      type: "meeting",
      status: "pending",
      scheduledAt: future2,
      durationMinutes: 90,
      agentId: agent2.id,
      clientId: client2.id,
      notes: "Premier rendez-vous découverte pour présenter notre offre.",
    },
    {
      type: "visit",
      status: "completed",
      scheduledAt: past1,
      durationMinutes: 45,
      propertyId: insertedProperties[3].id,
      agentId: agent2.id,
      clientName: "Léa Rousseau",
      clientEmail: "lea.rousseau@yahoo.fr",
      clientPhone: "06 30 00 00 04",
      notes: "Visite concluante, offre à venir.",
    },
  ]);
  console.log("Appointments created");

  // 7. Create estimations
  await db.insert(estimationsTable).values([
    {
      firstName: "Paul",
      lastName: "Vidal",
      email: "paul.vidal@gmail.com",
      phone: "06 40 00 00 01",
      address: "27 Rue du Soleil",
      city: "Marignane",
      postalCode: "13700",
      propertyType: "apartment",
      livingArea: 85,
      rooms: 4,
      bedrooms: 3,
      condition: "bon",
      hasParking: true,
      additionalInfo: "Appartement en excellent état, refait il y a 5 ans.",
      status: "pending",
      assignedAgentId: agent1.id,
    },
    {
      firstName: "Nathalie",
      lastName: "Schmitt",
      email: "n.schmitt@wanadoo.fr",
      phone: "06 40 00 00 02",
      address: "14 Impasse des Oliviers",
      city: "Istres",
      postalCode: "13800",
      propertyType: "house",
      livingArea: 140,
      rooms: 6,
      bedrooms: 4,
      condition: "à rénover",
      hasGarden: true,
      additionalInfo: "Maison des années 70, chauffage au fuel à remplacer.",
      status: "in_progress",
      assignedAgentId: agent1.id,
      estimatedMinPrice: "280000",
      estimatedMaxPrice: "320000",
    },
  ]);
  console.log("Estimations created");

  // 8. Activity logs
  await db.insert(activityLogsTable).values([
    { type: "property_created", description: `Nouveau bien créé : ${insertedProperties[0].title}`, entityId: insertedProperties[0].id, entityType: "property", actorId: agent1.id },
    { type: "property_published", description: `Bien publié : ${insertedProperties[1].title}`, entityId: insertedProperties[1].id, entityType: "property", actorId: agent1.id },
    { type: "lead_created", description: "Nouveau lead : Adrien Dupont", entityId: 1, entityType: "lead", actorId: agent1.id },
    { type: "appointment_booked", description: "Rendez-vous planifié : visite villa prestige", entityId: 1, entityType: "appointment", actorId: agent1.id },
    { type: "estimation_requested", description: "Demande d'estimation : 27 Rue du Soleil, Marignane", entityId: 1, entityType: "estimation", actorId: null },
  ]);

  console.log("Database seeded successfully!");
  console.log("\n=== Login credentials ===");
  console.log("Superadmin: superadmin@ida-immobilier.fr / superadmin123");
  console.log("Admin: admin@ida-immobilier.fr / admin123");
  console.log("Manager: manager@ida-immobilier.fr / manager123");
  console.log("Agent 1: agent1@ida-immobilier.fr / agent123");
  console.log("Agent 2: agent2@ida-immobilier.fr / agent123");
  console.log("Client 1: client1@example.fr / client123");
  console.log("Client 2: client2@example.fr / client123");
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
